### ISSUE TITLE
Conversor do polygon procura generator.cpp mesmo que ele não exista

### ISSUE THREAD

**Issue by danielsaad** [danielsaad/ds-contest-tools#73]
```Checking validator name
Traceback (most recent call last):
  File "/home/danielsaad/git/ds-contest-tools/run.py", line 5, in <module>
    main()
  File "/home/danielsaad/git/ds-contest-tools/ds_contest_tools/ds_contest_tools.py", line 57, in main
    options.function(options)
  File "/home/danielsaad/git/ds-contest-tools/ds_contest_tools/parsers/convert.py", line 132, in <lambda>
    from_parser.set_defaults(function=lambda options: process_convert_from(
  File "/home/danielsaad/git/ds-contest-tools/ds_contest_tools/parsers/convert.py", line 91, in process_convert_from
    get_polygon_problem(package_dir, local)
  File "/home/danielsaad/git/ds-contest-tools/ds_contest_tools/polygon_converter.py", line 581, in get_polygon_problem
    convert_problem(local, problem_id)
  File "/home/danielsaad/git/ds-contest-tools/ds_contest_tools/polygon_converter.py", line 543, in convert_problem
    copy_validator(problem_id)
  File "/home/danielsaad/git/ds-contest-tools/ds_contest_tools/polygon_converter.py", line 242, in copy_validator
    copy_source_files(content['result'], 'validator.cpp')
  File "/home/danielsaad/git/ds-contest-tools/ds_contest_tools/polygon_converter.py", line 179, in copy_source_files
    shutil.copy2(file, destination)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: '/home/danielsaad/git/maratona-utils/polygon-to-boca/F/temp_polygon_package/files/'```

**Comment by danielsaad** [comment]
Fixed by #74

**Comment by danielsaad** [comment]
Fixed by #74
